-- Modulo agenda: unidade de saude
CREATE TABLE unidade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255)   NOT NULL,
    latitude    NUMERIC(9, 6)  NOT NULL,
    longitude   NUMERIC(9, 6)  NOT NULL,
    criado_em   TIMESTAMP      NOT NULL DEFAULT now()
);

-- Modulo agenda: paciente
CREATE TABLE paciente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255)   NOT NULL,
    cns               VARCHAR(15)    NOT NULL UNIQUE,
    telefone          VARCHAR(20),
    latitude          NUMERIC(9, 6)  NOT NULL,
    longitude         NUMERIC(9, 6)  NOT NULL,
    data_nascimento   DATE           NOT NULL,
    criado_em         TIMESTAMP      NOT NULL DEFAULT now()
);

-- Modulo identidade: usuario de login (PACIENTE ou GESTOR)
CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL UNIQUE,
    senha_hash    VARCHAR(255)  NOT NULL,
    perfil        VARCHAR(20)   NOT NULL CHECK (perfil IN ('PACIENTE', 'GESTOR')),
    paciente_id   BIGINT        REFERENCES paciente (id),
    criado_em     TIMESTAMP     NOT NULL DEFAULT now()
);

-- Modulo agenda: vaga de atendimento
CREATE TABLE vaga (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id     BIGINT        NOT NULL REFERENCES unidade (id),
    especialidade  VARCHAR(100)  NOT NULL,
    profissional   VARCHAR(255)  NOT NULL,
    data_hora      TIMESTAMP     NOT NULL,
    status         VARCHAR(20)   NOT NULL
                   CHECK (status IN ('DISPONIVEL', 'RESERVADA', 'EM_CASCATA', 'OCUPADA', 'PERDIDA')),
    criado_em      TIMESTAMP     NOT NULL DEFAULT now()
);
CREATE INDEX idx_vaga_status ON vaga (status);
CREATE INDEX idx_vaga_especialidade ON vaga (especialidade);

-- Modulo agenda: agendamento (consulta marcada para uma vaga)
CREATE TABLE agendamento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id        BIGINT        NOT NULL REFERENCES vaga (id),
    paciente_id    BIGINT        NOT NULL REFERENCES paciente (id),
    status         VARCHAR(20)   NOT NULL
                   CHECK (status IN ('AGENDADO', 'CONFIRMADO', 'CANCELADO', 'REALIZADO', 'FALTOU')),
    confirmado_em  TIMESTAMP,
    criado_em      TIMESTAMP     NOT NULL DEFAULT now()
);
CREATE INDEX idx_agendamento_vaga ON agendamento (vaga_id);
CREATE INDEX idx_agendamento_paciente ON agendamento (paciente_id);
CREATE INDEX idx_agendamento_status ON agendamento (status);

-- Modulo fila: item na fila de espera
CREATE TABLE item_fila (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id               BIGINT        NOT NULL REFERENCES paciente (id),
    especialidade             VARCHAR(100)  NOT NULL,
    data_entrada              TIMESTAMP     NOT NULL DEFAULT now(),
    prioridade_clinica        SMALLINT      NOT NULL CHECK (prioridade_clinica BETWEEN 1 AND 5),
    aceita_chamado_imediato   BOOLEAN       NOT NULL DEFAULT true,
    raio_maximo_km            NUMERIC(6, 2) NOT NULL
);
CREATE INDEX idx_item_fila_especialidade ON item_fila (especialidade);
CREATE INDEX idx_item_fila_paciente ON item_fila (paciente_id);

-- Modulo fila: convite enviado a um candidato da fila durante a cascata
CREATE TABLE convite (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id            BIGINT        NOT NULL REFERENCES vaga (id),
    paciente_id        BIGINT        NOT NULL REFERENCES paciente (id),
    enviado_em         TIMESTAMP     NOT NULL DEFAULT now(),
    expira_em          TIMESTAMP     NOT NULL,
    status             VARCHAR(20)   NOT NULL
                       CHECK (status IN ('ENVIADO', 'ACEITO', 'RECUSADO', 'EXPIRADO')),
    ordem_na_cascata   INT           NOT NULL
);
CREATE INDEX idx_convite_vaga ON convite (vaga_id);
CREATE INDEX idx_convite_status ON convite (status);

-- Modulo risco: avaliacao de risco de falta de um agendamento
CREATE TABLE avaliacao_risco (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id  BIGINT        NOT NULL REFERENCES agendamento (id),
    score           INT           NOT NULL,
    classificacao   VARCHAR(10)   NOT NULL CHECK (classificacao IN ('BAIXO', 'MEDIO', 'ALTO')),
    avaliado_em     TIMESTAMP     NOT NULL DEFAULT now()
);
CREATE INDEX idx_avaliacao_risco_agendamento ON avaliacao_risco (agendamento_id);

-- Modulo risco: fatores que compoem o score de uma avaliacao (explicabilidade)
CREATE TABLE avaliacao_risco_fator (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_risco_id  BIGINT        NOT NULL REFERENCES avaliacao_risco (id),
    codigo              VARCHAR(50)   NOT NULL,
    descricao           VARCHAR(255)  NOT NULL,
    pontos              INT           NOT NULL
);
CREATE INDEX idx_avaliacao_risco_fator_avaliacao ON avaliacao_risco_fator (avaliacao_risco_id);
