-- Modulo fila: aviso de notificacao pendente de reenvio (fallback do Resilience4j
-- quando o notificacao-service esta indisponivel). O convite em si nunca depende
-- desta tabela - ela existe so para o reprocessamento automatico do aviso.
CREATE TABLE aviso_pendente (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    convite_id            BIGINT        NOT NULL REFERENCES convite (id),
    destinatario          VARCHAR(255)  NOT NULL,
    canal                 VARCHAR(20)   NOT NULL,
    mensagem              VARCHAR(500)  NOT NULL,
    status                VARCHAR(20)   NOT NULL CHECK (status IN ('PENDENTE', 'ENVIADO')),
    tentativas            INT           NOT NULL DEFAULT 0,
    criado_em             TIMESTAMP     NOT NULL DEFAULT now(),
    ultima_tentativa_em   TIMESTAMP     NOT NULL
);
CREATE INDEX idx_aviso_pendente_status ON aviso_pendente (status);
CREATE INDEX idx_aviso_pendente_convite ON aviso_pendente (convite_id);
